### ISSUE TITLE
Add support for Raw string Regex

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/better-cpp-syntax#236]
See https://solarianprogrammer.com/2011/10/16/cpp-11-raw-strings-literals-tutorial/
```
string raw_pattern=R"((\+|-)?[[:digit:]]+)";
```
We should probably combine/cleanup the string syntax (remove c_string) before adding this. When you @matter123 added support for assembly it reminded me of this.
We can probably pull the regex patterns from the raw string regex from [python](https://github.com/MagicStack/MagicPython), and honestly I'd be okay if they stay as TextMate patterns for now so long as they are bundled up well.

**Comment by matter123** [comment]
The particular syntax you posted is just a raw string (which the grammar supports). There does not appear to be a regex literal suffix

**Comment by matter123** [comment]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2053.html regex is one of the motivating examples, however. I am concerned that applying syntax highlighting for one particular format when raw string literals just as easily support html, markdown, SQL, and anything else you want may cause odd highlighting.

**Comment by jeff-hykin** [comment]
Yeah you're right, whats interesting is I think python just treats all raw strings as regex haha. I guess what we should do instead is disable all the escape patterns inside the raw string.

we could possibly have a pattern that finds regex initializers `regex a_pattern(r"test")` , and then if they contain a string literal we could highlight them with regex, but it would be kind of niche. 

Its a shame there is no option to add toggle-able patterns (textmate injections), and then we could make it an option to treat all raw strings as regex literals.

**Comment by matter123** [comment]
Blocked by https://github.com/Microsoft/vscode/issues/53885

**Comment by matter123** [comment]
One thing that can be done while 53885 is still open, is that C++ does allow for tagged raw string literals.  
From cppreference
`prefix(optional) R "delimiter( raw_characters )delimiter"`

So if delimiter is one of:
 - `_r`
 - `re`
 - `regex`
Then the raw string would have regex highlighting.

Example:
```c++
auto re_pattern = R"re([0-9'"\+]+)re";
```

**Comment by jeff-hykin** [comment]
(the merge fixed this)
