### ISSUE TITLE
Proper fix for catastrophic backtracking in function definition.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/better-cpp-syntax#320]
The curent fix for #287 is not a perfect fix. As https://github.com/jeff-hykin/cpp-textmate-grammar/issues/287#issuecomment-509021142 shows the issue can still appear. Additionally, this fix broke highlighting of function definitions when preceded by `extern "C"` (#319) or a macro.

This issue is to track any progress on preventing the function definition pattern from catostophically backtracking.

**Comment by matter123** [comment]
A less contrived example of how the fix is broken is when using fmtlib.
One might conceivably have the following snippet.
```
fmt::print("****** Warning {} Warning ******", msg);
```

**Comment by jeff-hykin** [comment]
Can we boil the example down and reproduce the catastrophic backtracking inside of a regex tool website? or do you think this is due to oniguruma?

**Comment by matter123** [comment]
From what I remember, the issue should be reproducible on regex testing sites.

**Comment by jeff-hykin** [comment]
Finally fixed this for good. It was the `std_space` pattern, making it greedy, reorganizing it a bit, and removing `\b` in favor of lookaheads/behinds overhauled performance
