### ISSUE TITLE
[C++] "struct foo::bar baz" confuses syntax highlighter

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#471]
Originally from @tbm0 in https://github.com/microsoft/vscode/issues/95834

Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [X] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
void test() {
    struct foo::bar baz;
    if (bar(baz,
            "%u;%ld",
            false);) {
        
    }
}
```

## It looks like:
https://user-images.githubusercontent.com/658101/79951062-54b03f00-8478-11ea-9e4f-908f36524509.png

## It should look like:
struct foo::bar baz confuses the C++ syntax hilighter.

Removing the "struct" prefix fixes things. It is redundant but it should still be OK to have. This worked alright in previous vscode versions. Reproduced with all extensions disabled.

VS Code version: Code 1.44.2 (ff91584, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-46-generic
Remote OS version: Linux x64 5.3.0-40-generic

**Comment by jeff-hykin** [comment]
fixed
