### ISSUE TITLE
Keyword highlights missing in template template parameter

### ISSUE THREAD

**Issue by HighCommander4** [jeff-hykin/better-cpp-syntax#492]
In the following code, the second `template` keyword on the indicated line is not highlighted:

```c++
template <template <typename T> class TT>   // <--
struct foo {};
```

If I give the template template parameter a default argument, the `class` keyword loses its highlighting too:

```c++
template <typename T>
struct vector {};

template <template <typename T> class TT = vector>  // <--
struct foo {};
```

Finally, if I omit the template parameter's own parameter `T` (which is valid), the `typename` keyword loses the highlighting too:

```c++
template <template <typename> class TT>  // <--
struct foo {};
```

**Comment by jeff-hykin** [comment]
fixed (well these cases, theres a new issue about the same fundamental behavior that is broken)
