### ISSUE TITLE
Inconsistent scope for pointers in parameter lists in C++

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/better-cpp-syntax#493]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C (no, scope is consistently keyword.operator.c)
- [X] This bug exists for C++
- [?] This bug exists for Objective-C
- [?] This bug exists for Objective-C++

## The code with a problem is:
```
struct s
{
    int func(char *s);
    char *s;
};

```

## It looks like:
Default dark theme.
Scope for "*" in the parameter is storage.modifier.pointer.cpp.
![image](https://user-images.githubusercontent.com/19859882/88712271-4bb1b800-d0ce-11ea-8473-d81be589c1f7.png)

## It should look like:
Scope for all other cases is keyword.operator.cpp (and for params in C). I don't know which case is correct, but the inconsistency seems incorrect.

Originally reported at https://github.com/microsoft/vscode-cpptools/issues/5844

**Comment by jeff-hykin** [comment]
fixed
