### ISSUE TITLE
Multiline comments after #define are broken

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#527]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C **(I checked, it doesn't repro with C, only C++)**
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C **(doesn't repro)**
- [ ] This bug exists for Objective-C++ **(doesn't repro)**

## The code with a problem is:
```c++
#define VAR 123 /*
* selfrnei
*/

#if VAR === 123 /*
* happens if 123
*/
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/103364853-0d765580-4abf-11eb-9074-1f4335a4a21b.png)

## It should look like:
![image](https://user-images.githubusercontent.com/38270282/103364900-241cac80-4abf-11eb-94ec-763d3707532f.png)

Original from @ashegoulding in https://github.com/microsoft/vscode/issues/110174

**Comment by WebDevAlok** [comment]
![Screenshot 2024-05-29 212425](https://github.com/jeff-hykin/better-cpp-syntax/assets/106583568/f7c126ad-37c2-4b86-9ff4-6448065f5caf)

The linter is not ignoring the comment block. Giving this error instead.
![Screenshot 2024-05-29 212743](https://github.com/jeff-hykin/better-cpp-syntax/assets/106583568/9cfe5dfd-9b20-449c-a998-8f1adb72ed67)

Please help me locate the relevant parsing logic. I would like to resolve this error.

**Comment by jeff-hykin** [comment]
@WebDevAlok sorry my thing only covers coloring, it doesn't lint or throw errors. I think you might be looking for this:
https://github.com/microsoft/vscode-cpptools/issues

Or more likely it is your specific C++ compiler / specific C++ project that is the cause of the error
