### ISSUE TITLE
The 'auto' keyword is not highlighted in C

### ISSUE THREAD

**Issue by interrupt-routine** [jeff-hykin/better-cpp-syntax#529]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [x] This bug exists for C
- [ ] This bug exists for C++
- [x] This bug exists for Objective-C
- [x] This bug exists for Objective-C++

## The code with a problem is:
```c
void function (void)
{
	register int a;
	static   int b;
	extern   int c;
	auto     int d;
}
```

## It looks like:
Theme : Dark+ (default dark)
![auto_bug](https://user-images.githubusercontent.com/77172657/104061356-b0824a00-51f8-11eb-9cc7-b20539b3bd6d.png)

## It should look like:
![correct_auto](https://user-images.githubusercontent.com/77172657/104061417-d576bd00-51f8-11eb-90de-929b1a24674d.png)

The `auto` keyword is not categorized as `storage.modifier.c` as it should be.

**Comment by jeff-hykin** [comment]
fixed
