### ISSUE TITLE
C++ : surrounding a #define-d value with parentheses breaks highlighting

### ISSUE THREAD

**Issue by interrupt-routine** [jeff-hykin/better-cpp-syntax#531]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
#define STRING ("abc")
#define NUMBER (10L)
```

## It looks like:
Theme : Dark+ (Default dark)
![problem](https://user-images.githubusercontent.com/77172657/104704265-b6a48900-5718-11eb-9f04-6282420425af.png)

## It should look like:
![correct](https://user-images.githubusercontent.com/77172657/104704304-c2904b00-5718-11eb-967d-1ddbf3006a2a.png)

**Comment by jeff-hykin** [comment]
fixed
