### ISSUE TITLE
String literals aren't handled correctly with this sample C++ code

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/better-cpp-syntax#551]
Checklist

- [Yes] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [No] This bug exists for C
- [Yes] This bug exists for C++
- [?] This bug exists for Objective-C
- [?] This bug exists for Objective-C++

## The code with a problem is:
```
#define A
struct foo
{
    /*d*/ void func(const char* c)
    {
        #ifdef FOO
            int i;
        #else
            func("" A ")");
        #endif
    }
};
```

## It looks like:
![image](https://user-images.githubusercontent.com/19859882/120533569-b6d6b580-c395-11eb-8157-a404a4de55df.png)

## It should look like:
![image](https://user-images.githubusercontent.com/19859882/120533607-c2c27780-c395-11eb-9a2b-84c598a7062a.png)

Originally reported at https://github.com/microsoft/vscode-cpptools/discussions/7627

**Comment by jeff-hykin** [comment]
This one is going to be tough to fix correctly

- Having the `{` on the next line makes it where textmate has no idea that it is inside of a function definition. 
-  so then it thinks that `func(""` is part of a constuctor. Inside of the constuctor `"" A` isn't valid
- instead its looking for type definitions and parameters

As with all things, there might be a hacky solution I'm not thinking of.

**Comment by jeff-hykin** [comment]
fixed with a hacky solution (not sure when)
