### ISSUE TITLE
String not always tokenized correctly

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#558]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```cpp
class TMyClass {
	QUERY_BEGIN("first part" MY_CONSTANT "second part");
}
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/125282823-166e9c00-e318-11eb-9be4-d52b84888715.png)

## It should look like:
![image](https://user-images.githubusercontent.com/38270282/125282898-27b7a880-e318-11eb-9300-ad37b3105987.png)

Originally reported in https://github.com/microsoft/vscode/issues/128333 by @LaseriumFloyd

**Comment by jeff-hykin** [comment]
fixed
