### ISSUE TITLE
thread_local not highlighted as keyword

### ISSUE THREAD

**Issue by HighCommander4** [jeff-hykin/better-cpp-syntax#561]
Checklist

- [x ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x ] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
int main() {
  thread_local int x;
}
```

## It looks like:

The `thread_local` keyword does not receive any textmate scope that would suggest it's a keyword or storage class specifier.

This has been a keyword in C++ since C++11

## It should look like:

The closest analogy is probably `static` which receives the scope `storage.modifier.specifier.static.cpp`. So perhaps `thread_local` should get `storage.modifier.specifier.thread_local.cpp`.

**Comment by jeff-hykin** [comment]
should be working on version `v1.15.8` 👍  thanks again for the PR @HighCommander4 

BTW the repo was overhauled so it should be a lot less of a mess to try and understand now
