### ISSUE TITLE
should the embedded language include `fileTypes`

### ISSUE THREAD

**Issue by asottile** [jeff-hykin/better-cpp-syntax#566]
running into an interesting bug with my text editor which uses these syntaxes to highlight code

it considers languages based on their root scope name sorted so unfortunately `source.cpp.embedded.macro.json` has higher priority than `source.cpp.json` and as such it gets matched for `.cpp` because the embedded grammar includes `fileTypes`

I'm not sure whether it should or not, and it fixes my problem if I remove `fileTypes` from the embedded syntax -- wondering if that would be an acceptable patch here!

thanks again for these syntaxes, they've been really useful!

EDIT: oops forgot to post my issue -- https://github.com/asottile/babi/issues/151

**Comment by jeff-hykin** [comment]
You're right Embdedded grammars shouldn't have filetypes. The main grammar should be the only thing that uses/imports the embedded grammar, so it shouldn't really matter. 

I went ahead and made a push that takes it out

**Comment by jeff-hykin** [comment]
Your project looks really interesting! Glad I could help! 

I've been wanting a better nano for quite a while.

**Comment by asottile** [comment]
thanks!  the patch on the main branch looks great!
