### ISSUE TITLE
Bitwise operators are not properly classified as such and resulting in incorrect syntax highlighting.

### ISSUE THREAD

**Issue by TheBeardOfTruth** [jeff-hykin/better-cpp-syntax#568]
Checklist
- [ N/A / yes ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
1. write any code using bitwise operators while using a theme that colours bitwise operators separately from other operators
2. observe that only right and left shift bitwise operators are coloured differently and that `|`, `&`, `^`, `~` aren't properly classified as `keyword.operator.bitwise`  when they ought to be, instead they are classified as `keyword.operator`. 
3. Consider that the logical equivalents:
`||`, `&&` , `!` are classified as `keyword.operator.logical`, this is a discrepancy that makes it impossible to properly colour bitwise operators differently from normal operators.

An example:

```cpp
constexpr void flip_bit(uint32_t *arr, uint32_t bit)
{
	uint32_t indx  = bit >> _ct_log2(size);
	uint32_t mask  = bit & x - 1;
	arr[indx] ^= (1 << mask);
}
```

Additionally `&=`, `|=` et. al are classified as `keyword.operator.compound`, it would be nice if there was a `keyword.operator.bitwise.compound` but I'm not convinced that scope even exists so that's probably unreasonable.

## It looks like:
![image](https://user-images.githubusercontent.com/53689060/129199120-c94b4cc3-bebd-4293-94d8-927c2bb26523.png)

## It should look like:
The bitwise operators should properly be classified as such so they will use the bitwise operator colour.

**Comment by jeff-hykin** [comment]
Should be fixed now 👍 I also went ahead and added some specificity to the arithmetic operators as well
