### ISSUE TITLE
Highligting logical operator keywords 

### ISSUE THREAD

**Issue by bitsauce** [jeff-hykin/better-cpp-syntax#570]
I may be doing something wrong here, but I am unable to get VSCode to highlight any logical operator keywords in my cpp files. I've found that the `and`, `or`, `not` keywords can be recolored using the `keyword.operator` scope, however, this also colors other operators, such as `=`/`+`/etc..

Similar issue for lua: https://github.com/microsoft/vscode/issues/71504

EDIT: Forgot to mention I'm using the Dark+ theme

## The code with a problem is:
```
if (not a and (b or c)) { ... }
```

## It looks like:
![logical_operators](https://user-images.githubusercontent.com/3323853/135906557-5d48c79f-b42d-4cf8-9919-6b7c7d25dee9.png)

## It should look like:
`and`, `or` and `not` should be purple like the preceding `if` (or some other color).

**Comment by jeff-hykin** [comment]
Try running the ">Developer: Inspect Editor Tokens and Scopes" in the command pallet (cmd/ctrl+P) it'll show you all the scopes then you can get the full name instead of just `keyword.operator`

**Comment by jeff-hykin** [comment]
![Screen Shot 2021-10-04 at 2 29 29 PM](https://user-images.githubusercontent.com/17692058/135912605-c4cd5091-08b7-4bed-a1e6-2521efbd14ff.png)

**Comment by jeff-hykin** [comment]
there's a scope called `keyword.operator.wordlike` that is probably the one you want to use. It'll work for operators like `new` too

**Comment by bitsauce** [comment]
Thanks Jeff! Got it working now by specifying `keyword.operator.and.cpp`, `keyword.operator.or.cpp`, etc. 🙂 

One question though, do you know if there is a reason these keywords don't work out of the box? Or did I just mess up my dev environment somehow maybe?

**Comment by jeff-hykin** [comment]
> a reason these keywords don't work out of the box?

It sounds like the theme just chooses not to highlight operators . They might consider that a bug but they could consider it a feature 


I personally recommend any theme other than the default theme. (and I really mean ANY theme)
Here are some pretty good ones:

- [Material Theme](https://material-theme.site/)
- [Noctis](https://marketplace.visualstudio.com/items?itemName=liviuschera.noctis)
- [XD Theme (<- biased cause its mine)](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.xd-theme)
- [Kary Pro Colors](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes)
- [One Monokai Theme](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai)
- [Winteriscoming](https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming)
- [Popping and Locking](https://marketplace.visualstudio.com/items?itemName=hedinne.popping-and-locking-vscode)
- [Syntax Highlight Theme](https://marketplace.visualstudio.com/items?itemName=peaceshi.syntax-highlight)
- [Default Theme Enhanced](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes)
