### ISSUE TITLE
C++20 constinit keyword is not highlighted

### ISSUE THREAD

**Issue by soroshsabz** [jeff-hykin/better-cpp-syntax#575]
This is a new keyword in C++20.

Some example usages can be found at https://en.cppreference.com/w/cpp/language/constinit. Currently, none of them are highlighted (scope is just source.cpp).

**Comment by jeff-hykin** [comment]
Thanks for linking the docs here. And connecting issues to the old C++2020 issue.

Most of the 2020 features still have not been added. They will get added at some point in the next year but PR's are welcome.
