### ISSUE TITLE
Parameter types are incorrectly confused for parameter identifiers and color highlighted as such.

### ISSUE THREAD

**Issue by 103sbavert** [jeff-hykin/better-cpp-syntax#580]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [x] This problem exists even with all the other extensions disabled.
- [x] The problem doesn't exist for C++.

## The code with a problem is (A function declaration without the paramter identifier):
```c
void fn(unsigned int);

void fn(const char[])
```

## It looks like:
![image](https://user-images.githubusercontent.com/65838896/145519359-aefa722b-0f99-4240-a94c-d18ea0297d43.png)

## It should look like:
As you can see, in the code above with the C programming language, both `int` and `char` should be colored dark blue instead of light blue (which is used for parameter identifiers in VSC). The problem is only persistent with C and **not** C++. `int` and `char` being keywords should be highlighted with dark blue as all other keywords are but that isn't the case.

**Comment by 103sbavert** [comment]
Another issue I noticed, unlike most IDEs, in VSC most keywords are dark blue but not all. For example the return keyword is pinkish. I don't think that's a good idea. All keywords should be the same color or at least we should be able to make them all the same color.

**Comment by yume-chan** [comment]
> Looks very similar to [jeff-hykin/better-cpp-syntax#200](https://github.com/jeff-hykin/better-cpp-syntax/issues/200).
> 
> [jeff-hykin/better-cpp-syntax@ad31cfa](https://github.com/jeff-hykin/better-cpp-syntax/commit/ad31cfa8d06699226827ae126f2366e08e88be26) only fixed its cpp grammar, and indeed the issue doesn't happen when set to cpp mode.
> 
> ![image](https://user-images.githubusercontent.com/1330321/145438839-d3f576af-818d-41e2-8cac-bf0e41f11853.png) (c)
> 
> ![image](https://user-images.githubusercontent.com/1330321/145438881-eaab1861-d893-4b25-91a2-fa4f9ed131b6.png) (cpp)

Copied my reply from https://github.com/microsoft/vscode/issues/138695#issuecomment-990025943

**Comment by jeff-hykin** [comment]
> Another issue I noticed, unlike most IDEs, in VSC most keywords are dark blue but not all. For example the return keyword is pinkish. I don't think that's a good idea. All keywords should be the same color or at least we should be able to make them all the same color.

@sbeve72 you can customize any theme for any language to have exactly the colors you want just by editing your settings. Short tutorial [here](https://jeffhykin.medium.com/how-to-customize-your-vs-code-text-colors-c0191155f41a?source=your_stories_page----------------------------------------) 

(I don't control the default theme btw)

Keyword is pretty broad. There's operators, control flow, entity declarations, built in primitives, built-in modifiers, built in pointers, built in macros, built in functions, type casting,  access specifiers, and more. It would be a major loss of information if the parser didn't distinguish between them. If you want to make them all the same color you're welcome to find or make a theme that does, but the capability will exist for theme designers who want to deeply color different code functionality.

**Comment by 103sbavert** [comment]
Can I do anything about the bug that I mentioned in the original comment? Is there a way to customize the theme to fix that?

**Comment by jeff-hykin** [comment]
You can change the color, but the original thing is a legitimate bug that is broken on the parser side. Right now the C parser needs to be rewritten, and that coloring is happening because it thinks int and char are parameters instead of types
