### ISSUE TITLE
Variable template incorrectly recognized as comparison operator

### ISSUE THREAD

**Issue by jgcodes2020** [jeff-hykin/better-cpp-syntax#581]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```c++
#include <iostream>

template <bool T>
constexpr bool var_template = T;

template <bool T>
struct obj_template {
  static constexpr bool value = T;
};

int main() {
  std::cout << var_template<true> << obj_template<true>::value;
}
```

## It looks like:
![image](https://user-images.githubusercontent.com/35639051/146295832-a688439f-ebf0-4cc2-a5b8-e8a56f27cbb7.png)
with the One Monokai theme

## It should look like:
The `< `and `>` tokens next to `var_template` in `var_template<true>` should get the `punctuation.section.angle-brackets.begin.template.call.cpp` and `punctuation.section.angle-brackets.end.template.call.cpp` scopes respectively.

They don't.

**Comment by jeff-hykin** [comment]
fixed, not sure when it was fixed though
