### ISSUE TITLE
C++ syntax is currently not highlighted as shown in the example screenshots

### ISSUE THREAD

**Issue by sandeepmvd** [jeff-hykin/better-cpp-syntax#586]
Is there a log i can see why the highlighting is not working although i enabled the extension?
it could probably be because the project is very big and is hosted remotely. Is there a way i can force it on a particular file after i open it?

**Comment by jeff-hykin** [comment]
There is a way to use the "inspect element" command to see exactly what each thing is labelled as.

The example screenshots are pretty old so it's very possible the Material theme has changed, and the default VS Code syntax has probably also been updated.

**Comment by sandeepmvd** [comment]
![Screenshot from 2022-04-18 08-43-18](https://user-images.githubusercontent.com/5645667/163748930-259dd9dc-b9cf-4a42-a7b6-741aec0d4ac2.png)

This is the screenshot.
Do you think better C++ syntax is effective?
Also, can you please tell me how do i inspect element inside vscode?

**Comment by jeff-hykin** [comment]
Yes that is how it is supposed to look. Ctrl+shift+P and then type "inspect scopes"

**Comment by sandeepmvd** [comment]
Thank you. I dont see the option of inspect element after ctrl+shift+P
Thank you. Let me close the issue.

**Comment by jeff-hykin** [comment]
Oh looks like they changed it to "inspect editor token and scopes" which is a better name
