### ISSUE TITLE
Code conversion bug? `[^Pattern.new(\n  match: \\/\\w\\/,\n)]`

### ISSUE THREAD

**Issue by RedCMD** [jeff-hykin/better-cpp-syntax#588]
When scrolling through the `cpp/tmLanguage.json` file; I noticed this very weird character-class: `[^Pattern.new(\n  match: \\/\\w\\/,\n)]`
I assume it was not intentional
https://github.com/jeff-hykin/better-cpp-syntax/blob/219665b119c368c7188f0bbc059582a15a5634e4/syntaxes/cpp.tmLanguage.json#L7220
![image](https://user-images.githubusercontent.com/33529441/169782879-7e3d5b48-ffbb-4a6c-bfe1-ec240cf106e3.png)

**Comment by jeff-hykin** [comment]
That is concerning, and definitely a bug. Really strange that it only happened for member access too

**Comment by jeff-hykin** [comment]
Alright fixed it, thanks for the catch

**Comment by RedCMD** [comment]
`[^\\w]` is the same as `\\W`
