### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [jeff-hykin/better-cpp-syntax#592]
Hi there @jeff-hykin 👋, 
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [OpenVSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is OpenVSX? Why does it exist?

OpenVSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/) based IDEs, and so on.

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the command `ovsx publish` to publish your plugin. See this example from RedHat publishes their Java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)
You can also find [an example PR](https://github.com/PeterWone/vsc-print/pull/121) that contributes a release GitHub Action which publishes to GitHub, MS and OpenVSX at the same time.

I'd love to help if there are problems with publishing, because I would really love if the extension was accessible for VS Code forks as well.

**Comment by jeff-hykin** [comment]
I would love to. 

Sadly I'm having trouble with the process. Everything was followed but I'm ending up here: 
(auth token removed from image for obvious reasons)
<img width="1376" alt="Screen Shot 2022-06-16 at 11 34 39 AM" src="https://user-images.githubusercontent.com/17692058/174121335-cc79f6d9-27c0-40f6-a9fb-64bdbfb2cdac.png">

It seems I'm unable to make a namespace, or use an existing one. The linked document has a lot of info, but I don't see a "do this to publish" part
<img width="903" alt="Screen Shot 2022-06-16 at 11 36 57 AM" src="https://user-images.githubusercontent.com/17692058/174121830-69311dde-4e11-4eab-98ff-bd82d50539d2.png">

**Comment by filiptronicek** [comment]
@jeff-hykin thanks a lot for the efforts. This seems to be happening due to the namespace already being owned by the service account @open-vsx. This means unfortunately you will have to claim the namespace via a GitHub issue in https://github.com/EclipseFdn/open-vsx.org [[1](https://github.com/EclipseFdn/open-vsx.org/issues/new/choose)] - this should hopefully be straight forward and take just a short while to claim.

Feel free to cc me in the issue and I will make sure it's processed ASAP 🙂.

**Comment by jeff-hykin** [comment]
Done (been done, just now closing)
