### ISSUE TITLE
Dark+ Issue

### ISSUE THREAD

**Issue by devloos** [jeff-hykin/better-cpp-syntax#600]
Hey guys I am using dark+ in vscode and I was cleaning up some of my extensions and I could not find a difference when `Better C++ Syntax` was enabled or disabled using dark+. Have I been running it wrong this whole time or is there a minimal difference when using dark+?

**Comment by jeff-hykin** [comment]
VS Code actually has well-tested versions of this extension built into it. It's a rolling release so installing the extension is basically getting the beta C++ syntax.

If nothing has been added recently (like last 1-3months) it's going to look the same as normal VS Code.

**Comment by devloos** [comment]
Ooo I see very well then thank you @jeff-hykin
