### ISSUE TITLE
C++ alignas keyword not ricognized

### ISSUE THREAD

**Issue by AlessandroScrem** [jeff-hykin/better-cpp-syntax#601]
![image](https://user-images.githubusercontent.com/48774358/183298462-095e0edc-398b-4643-849c-c7ed6a1181d0.png)

c++ Keyword alignas afert struct declaration is not ricognized , as Visualstudio can do.

Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

thanks

**Comment by jeff-hykin** [comment]
Seems to work for me, maybe it is the theme? Let me know if its still a problem and I'll reopen the issue
<img width="890" alt="Screen Shot 2022-10-06 at 9 34 19 AM" src="https://user-images.githubusercontent.com/17692058/194341279-30a56838-c60d-4d0f-b132-65f0e662bd03.png">
