### ISSUE TITLE
Incorrect highlighting of comments following `#error`/`#warning` directives w/o message

### ISSUE THREAD

**Issue by per1234** [jeff-hykin/better-cpp-syntax#611]
Inline comments following `#error` and `#warning` directives which do not include the [optional](https://timsong-cpp.github.io/cppwp/n4868/cpp.error) message string are highlighted incorrectly.

## Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:

```cpp
#warning bar  // Coloration of comment is as expected
#warning  // Coloration of comment is NOT as expected
#error foo  // Coloration of comment is as expected
#error  // Coloration of comment is NOT as expected
```

## It looks like:

Using "Dark+" theme:

![image](https://user-images.githubusercontent.com/8572152/198859025-88f3191e-83d2-4110-b719-9ea5bfe758d1.png)

## It should look like:

Comments should be highlighted consistently regardless of whether or not the `#error` or `#warning` directive is followed by a message.

**Comment by jeff-hykin** [comment]
should now be fixed with `v1.17.2`
