### ISSUE TITLE
Incorrect tokenization of mid-line comment

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#617]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```cpp
a < (/* > (*/ b)
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/206155274-a15ba569-2551-4f94-bcf8-fcd914f873e0.png)

## It should look like:
The `/* > (*/` should be tokenized as a comment.

Originally from @hediet  in https://github.com/microsoft/vscode/issues/168290

**Comment by jeff-hykin** [comment]
Partly fixed with `v1.17.1` The fix is imperfect, but a perfect fix isn't possible with textmate
