### ISSUE TITLE
Objective-C Language syntax highlighting doesn't know documentation comments

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#628]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

If Disabling that^ makes the problem go away, then follow this to make an issue on the C++ extension:
https://github.com/microsoft/vscode-cpptools/issues/new/choose

## The code with a problem is:
```
/// This is a doc comment
int main(int argc, char **argv) {
	return 0;
}
```

## It looks like:

Works correctly in C but not in Objective-C. Textmate scope for comments **and** documentation comments in Objective-C is both:

```
comment.line.double-slash.objc
meta.block.objc
source.objc
```

## It should look like:

In a pure C file, the scope for a normal comment is:

```
comment.line.double-slash.c
meta.block.c
source.c
```

but for a documentation comment it is:

```
comment.line.double-slash.documentation.c
meta.block.c
source.c
```

Originally from @CodingMarkus in https://github.com/microsoft/vscode/issues/175155

**Comment by alexr00** [comment]
Ah, sorry, I meant to file this in https://github.com/jeff-hykin/better-objc-syntax.

**Comment by jeff-hykin** [comment]
No problem, closing in favor of https://github.com/jeff-hykin/better-objc-syntax/issues/3
