### ISSUE TITLE
colorization of tab character "\t" in string does not work properly

### ISSUE THREAD

**Issue by bernd4** [jeff-hykin/better-cpp-syntax#639]
Hello,

Please check this link.
https://github.com/microsoft/vscode/issues/185246

The colorization of escaped special characters in strings is acting funny.
Below is an exercise from the learn.microsoft as example code.

The lighter orange color doesn't render consistantly.

![image](https://github.com/jeff-hykin/better-cpp-syntax/assets/122995488/95caef87-f24f-459b-8585-ae01cd781435)

![image](https://github.com/jeff-hykin/better-cpp-syntax/assets/122995488/1f34e308-a918-45ef-a8f6-085b37b5ce4a)

[Program.cs.txt](https://github.com/jeff-hykin/better-cpp-syntax/files/12036787/Program.cs.txt)

These are my enabled extensions
<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
ng-template | Ang | 16.0.0
vscode-html-css | ecm | 1.13.1
dotnet-test-explorer | for | 0.7.8
remotehub | Git | 0.60.0
csharpextensions | kre | 1.7.3
csharp | ms- | 1.26.0
azure-repos | ms- | 0.36.0
remote-repositories | ms- | 0.38.0
vsliveshare | ms- | 1.0.5873
material-icon-theme | PKi | 4.28.0
LiveServer | rit | 5.7.9

</body>
</html>

**Comment by jeff-hykin** [comment]
Sorry to make you move your issue again @bernd4 I think @RedCMD missed the "C#" tag.
I would move the issue myself, but I'm actually not sure what the upstream source for C# is.

@alexr00 probably knows though.

Also, while you're here Alex, I just wanted to give you a heads up that I temporarily switched better-cpp to GPLv3. I know that's not the most exciting thing to hear, and I don't know if I'm going to keep it under GPLv3. I just had some changes and wanted some more time to consider it before publishing the changes with a more permissive license. I'll @ you in a issue if I change it back to MIT or something simlar. My other syntaxes are all still MIT and I plan to keep them under MIT, its just C++ at the moment.

**Comment by alexr00** [comment]
@bernd4 I moved the issue for you here: https://github.com/dotnet/csharp-tmLanguage/issues/275

@jeff-hykin thank you for the heads up. I will freeze our updating of your C++ grammar.
