### ISSUE TITLE
Add semantic colorization for c++23 #elifdef and #elifndef

### ISSUE THREAD

**Issue by avolden** [jeff-hykin/better-cpp-syntax#641]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```cpp
#include <iostream>

int main(int argc, const char ** argv)
{
    #ifdef _WIN32
    std::cout << "Hello World Windows" << std::endl;
    #elifdef __linux__
    std::cout << "Hello World Linux" << std::endl;
    #endif
    return 0;
}
```

## It looks like:
![image](https://github.com/jeff-hykin/better-cpp-syntax/assets/11920536/4561b160-912e-4bbb-80cd-8f4ccf02293f)
using Material Theme (Community Material Theme Darker)

## It should look like:
The #elifdef and #elifndef sould be colored correctly, as this is a supported and standard preprocessor directive from c++23

**Comment by jeff-hykin** [comment]
man why does the C++ team keep adding junk like this 🙄

anyways, added support in `v1.21.1`, you should see a huge change in type highlighting as well.
