### ISSUE TITLE
Wrong Token Scope for Typename

### ISSUE THREAD

**Issue by rjabkov** [jeff-hykin/better-cpp-syntax#643]
both tested, no diff:
`"C_Cpp.enhancedColorization": "disabled"`
`"C_Cpp.enhancedColorization": "ebabled"`

Colors for "T" and "y/x" in the following code are same; moreover, there's the same token scope!
```
    template<typename T>
    struct RstrPnt
    {
        RstrPnt() = default;
        RstrPnt(T y_, T x_)    : y(y_), x(x_) {}
        T y = 0;
        T x = 0;
    };

```
## choosing T
![bug1](https://github.com/jeff-hykin/better-cpp-syntax/assets/68894008/0137866c-35a6-4440-9277-1ccd0a7bc5dc)

## choosing y
![bug2](https://github.com/jeff-hykin/better-cpp-syntax/assets/68894008/00a93bbe-bd9c-4a01-bb68-a207528f0584)
 
## my settings.json's fragment
![settjson](https://github.com/jeff-hykin/better-cpp-syntax/assets/68894008/f4bf38c2-ab0f-42cc-8943-0f0efee36f36)

**Comment by jeff-hykin** [comment]
not sure when this was fixed, but it looks fixed now!
