### ISSUE TITLE
new version is not publish to vscode market?

### ISSUE THREAD

**Issue by yyjdelete** [jeff-hykin/better-cpp-syntax#644]
The version in this repo is already updated to `1.21.1`, but the one in [vscode market](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) is still `1.17.2`(2022-12-11)
And no github released, where can I get new version of the extension?

**Comment by jeff-hykin** [comment]
Sorry about that, my vscode auth token expired and I just haven't gotten around to updating it. 

The extension is published on 
https://open-vsx.org/ if you want to grab changes from there. I'll also consider making auto releases of the visx files for manual download install
