### ISSUE TITLE
The keyword constexpr is not highlighted

### ISSUE THREAD

**Issue by 24bit-xjkp** [jeff-hykin/better-cpp-syntax#651]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```cpp
int main()
{
    constexpr std::size_t highlight{};
    const ::std::size_t highlight2{};
    ::std::size_t const highlight3{};
    ::std::size_t constexpr highlight4{};
    constexpr ::std::size_t no_highlight{};
}
```

## It looks like:
![image](https://github.com/jeff-hykin/better-cpp-syntax/assets/63223769/b5be06c2-1fa8-4557-841a-71d9f0c52de9)

## It should look like:
The keyword `constexpr` should be highlighted.

**Comment by jeff-hykin** [comment]
fixed now!
