### ISSUE TITLE
C++ syntax highlighting falls apart after specific struct syntax

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#652]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

If Disabling that^ makes the problem go away, then follow this to make an issue on the C++ extension:
https://github.com/microsoft/vscode-cpptools/issues/new/choose

## The code with a problem is:
```c++
struct foo
{
	void (*bar1)() noexcept;
	void (*bar2)() noexcept;
	void (*bar3)() noexcept;
};

void baz()
{
	static_assert(false, "some string");
	int x = 0;
}
```

## It looks like:
In latest insiders with the default theme
![image](https://github.com/microsoft/vscode/assets/484784/f6eb2eb7-a002-487f-bd7b-7e428a9a85fb)

More issues are apparent depending on the theme being used
![image](https://github.com/microsoft/vscode/assets/484784/5f592f45-1028-4745-a57a-5ef2f39b4070)

## It should look like:
Here's the snippet again with some of the issues annotated. It appears as though the parser gets confused on the first function pointer and essentially thinks all the things after it are parameters in the function pointer type.
```
struct foo
{
    void (*bar1)() noexcept;        // noexcept is entity.name.type.parameter, should be storage.modifier.special.functional.post-parameters.noexcept.cpp
    void (*bar2)() noexcept;        // bar2 is variable.parameter.pointer.function, should be variable.other.pointer.function.cpp
    void (*bar3)() noexcept;
};                                  // } is meta.parameter.cpp, should be punctuationsection.block.end.bracket.curly.struct.cpp

void baz()                          // baz is entity.name.type.parameter.cpp, should be entity.name.function.definition.cpp
{
    static_assert(false, "string");
    int x = 0;                      // line is string.quoted.double.cpp
}
```

Originally from @akbyrd in https://github.com/microsoft/vscode/issues/202365

**Comment by jeff-hykin** [comment]
@akbyrd thank you for including the scopes, that's super helpful. I think you're right, something is confusing the function pointer pattern and then it never closes. I bet it'll be an easy fix so I'll take a look when I get the chance
