### ISSUE TITLE
The C syntax is different from the C++ syntax

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/better-cpp-syntax#70]
Right now the C++ and C syntax are being generated completely separately. I am familiar with C++ and most of my fixes have been exclusively for C++ even if they should be applicable to C.

There have already been issues posted about this difference.
* #46
* #47 

This issue is a log and general discussion about how to keep the C syntax in sync with the C++ Syntax without breaking compatibility on either side.

### update:
I've decided to fix all of C++ first and then fix C. If there's a major issue with the C syntax, then it will get fixed separately.

I'm going to use this post as a log to keep track of all the non-major issues with the C syntax.

1. Percent Escapes in C 
`sscanf(user_input, "%c %[^\n]", &arg0, arg_str); // reads char into arg0, the remainder until \n to arg_str`
atom/language-c#222
atom/language-c#70
2. `struct f foo` is missing highlighting
#46
```
/* Forward Declaration */
struct A b;
enum B c;
union C d;

/* Function Declaration */
void a(struct A b);
void b(enum B c);
void c(union C d);
void d(A b);

/* Definition */
struct A {
	enum B c;
	union C d;
};
enum B {
	struct A d;
	union C d;
};
union C {
	struct A b;
	enum B c;
};
```
3. Trigraph support
#32 
`const char * a = "foo ??/" ??/??/";`

**Comment by jeff-hykin** [comment]
What is your opinion on temporarily using the C++ syntax as the C syntax since C++ is almost a perfect superset of C. @matter123 ?

Or maybe having it be a superset with the exception of replacing `cpp_tokens` with `c_tokens`

**Comment by matter123** [comment]
I have a very experimental way to "diff" grammars, let me compare the C and C++ on the linux kernel. Give me about 10 minutes to set that up. Sharing common patterns is probably the best though.

**Comment by matter123** [comment]
[linux.log](https://github.com/jeff-hykin/cpp-textmate-grammar/files/3062057/linux.log)

Only a small fraction of the files as the diff tool crashed. However, most changes from the C++ grammar look harmless. Have a better source of C files?

**Comment by jeff-hykin** [comment]
Sadly I don't but I might know some people that do. I'll check in with them. This is a good idea for testing.

**Comment by matter123** [comment]
Yeah, it can catch some slightly hard to find bugs like anonymous struct https://github.com/jeff-hykin/cpp-textmate-grammar/pull/57#issuecomment-481502001, but it is currently pretty rough.

**Comment by jeff-hykin** [comment]
So long as themers don't have an issue, it might be best to fully clean up the C++ code first and then once it is, we work on back-porting everything to C.

If themers do have an issue, then I think the best solution will be to use the C++ highlighting for both until it is cleaned up. I looked up the differences in the C syntax that were not in C++ and there are only a handful of cases.

**Comment by matter123** [comment]
C supports some pretty fancy designated initalizers `int a[10] = { [5] =5,0}` and `{.a.v[0].c = {.a ={[1]='q'}}` are both valid.

**Comment by jeff-hykin** [comment]
I guess we will have to see how the C++ syntax handles that.  So long as it doesn't break the syntax it will probably still be an improvement over what it currently is highlighted with.

**Comment by matter123** [comment]
C | C++
--- | ----
![Screenshot from 2019-04-11 21-42-06](https://user-images.githubusercontent.com/714007/56012766-bef9a580-5ca2-11e9-950e-9ac1d5d6f389.png) | ![Screenshot from 2019-04-11 21-42-30](https://user-images.githubusercontent.com/714007/56012767-c02ad280-5ca2-11e9-9a3a-64bfcaa4ccc0.png)

So currently C and C++ offer similar coloring of the provided designated initializer example. C++ does forget about the character literal, however.

**Comment by tristan957** [comment]
I have a C repo located at https://git.sr.ht/~tristan957/tllt-cp that might be able to serve as a good test for diffing the C/C++ grammars. About 3000 lines of C code that uses many parts of the language.

**Comment by matter123** [comment]
[tllt-cp.log](https://github.com/jeff-hykin/cpp-textmate-grammar/files/3087159/tllt-cp.log)

So the first item I noticed if we are to share generators, the existing pattern tags that manually add, `.cpp` have to go.

* C++ drops `meta.function`, but being a meta scope is probably not all that important.
* in `err->message` message is tagged as `variable.other.member` in C but `variable.other.property` in C++
* C++ drops `punctuation.section.parameters.end.bracket.round` from `[]`
* again the scope changes from `variable.object` to `variable.other.object`
* scope changes from `punctuation.section.parens.block` to `meta.block.parens`

Thanks @tristan957

**Comment by tristan957** [comment]
Cool glad I could be of assistance

**Comment by jeff-hykin** [comment]
I just realized #107 blocks copying the C++ syntax to C. It would completely wreck any language that is inheriting from the C language.

**Comment by matter123** [comment]
I am going to use this comment to list patterns that can be shared between C and C++
* identifiers
  * both  C and C++ agree on the character set that can be in an identifier including universal character names
* numbers
  * C has no support for user-defined literals or numeric separators but this should not be an issue as quoting from the C11 standard 6.4/5 (non normative)
> EXAMPLE 1 The program fragment 1Ex is parsed as a preprocessing number token (one that is not a
valid floating or integer constant token), even though a parse as the pair of preprocessing tokens 1 and Ex
might produce a valid expression (for example, if Ex were a macro defined as +1). Similarly, the program
fragment 1E1 is parsed as a preprocessing number (one that is a valid floating constant token), whether or
not E is a macro name.

tokenization treats any sequence of characters starting with a number as a number
* tri and digraphs
* TODO

**Comment by tristan957** [comment]
Are you guys noticing that true, false, and NULL in C++ are not highlighted the same as in C?

**Comment by matter123** [comment]
Yeah that's a regressions

**Comment by matter123** [comment]
@jeff-hykin Is there a preferred way for shared patterns to add to the current grammars repository?

**Comment by jeff-hykin** [comment]
Ah this is really old, I was thinking the file that imports the shared thing would add it to it's grammar.

**Comment by jeff-hykin** [comment]
In general though, I think most of the sharing is going to happen once C++ has it's type system figured out. Then the common stuff will be extracted and a good sharing system will be implemented.

**Comment by jeff-hykin** [comment]
C syntax has finally been separated/moved to https://github.com/jeff-hykin/better-c-syntax !
